version: '3.8'

services:
  bot:
    env_file: .env
    build: .
    container_name: bot
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network
    

  db:
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:5432"
    container_name: lesson_shedule_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge